# See https://github.com/inspectIT/inspectit-oce/blob/0.1.M1/inspectit-oce-core/src/main/resources/config/default.yml
# for all the configuration options.
inspectit:
  logging:
    debug: true
  config:
    file-based:
      frequency: 1s
      
  instrumentation:
    scopes:
      servlet_service:
        interfaces:
          - name: javax.servlet.Servlet
        methods:
          - name: service
        advanced:
          instrument-only-inherited-methods: true
          
      methods_with_request_mapping:
        methods:
          - annotations:
              - name: org.springframework.web.bind.annotation.GetMapping
        advanced:
          disable-safety-mechanisms: true
          
    dataproviders:
      get_bt_from_request_mapping:
        imports:
          - org.springframework.web.bind.annotation
        input:
          methodName: String
          clazz: Class
          parameterTypes: Class[]
        value-body: | 
          GetMapping gm = (GetMapping) (clazz.getDeclaredMethod(methodName,parameterTypes).getAnnotation(GetMapping.class));
          return gm.value()[0];
      get_request_servlet_path:
        imports:
          - javax.servlet
          - javax.servlet.http
        input:
          arg0: ServletRequest
        value-body: |
          if(arg0 instanceof HttpServletRequest) {
            return ((HttpServletRequest)arg0).getServletPath();
          }
          return null;
      get_first_non_null:
        input:
          val1: Object
          val2: Object
        value: "val1==null? val2 : val1"
          
    rules:
      servlet_service:
        scopes: {servlet_service : true}
        entry:
          method_entry_time: { provider: timestamp_nanos }
          temp: {provider: get_request_servlet_path}
          business_transaction:
            provider: get_first_non_null
            data-input: {val1: business_transaction, val2: temp}

        exit:
          method_duration:
            provider: elapsed_millis
            data-input:
              sinceNanos: method_entry_time
        metrics:
          '[http/responsetime]' : method_duration
          
      fetch_bt_from_request_mapping:
        scopes: {methods_with_request_mapping : true}
        entry:
          temp: { provider: get_bt_from_request_mapping }
          business_transaction:
            provider: get_first_non_null
            data-input: {val1: temp, val2: business_transaction}
    data:
      business_transaction:
        up-propagation: JVM_LOCAL
        down-propagation: JVM_LOCAL
      temp:
        down-propagation: NONE
        is-tag: false

  metrics:
    definitions:
      '[http/responsetime]':
        unit: ms
        views:
          '[http/responsetime/count]': 
            aggregation: COUNT
            tags: {business_transaction: true}
          '[http/responsetime/sum]': 
            aggregation: SUM
            tags: {business_transaction: true}
          